### ISSUE TITLE
Support Upload? [PUT]

### ISSUE THREAD

**Issue by McPo** [IndigoUnited/node-request-progress#34] opened 2017-03-10 16:54 UTC
It appears the library only supports download progress. Is there a chance of supporting uploading progress (namely PUT request). If not, it might be worth mentioning in README.

Im aware that the following code is where the hooks are added, so if theres a hook for upload progress it should be possible.

```
// Attach listeners
    request
    .on('request', onRequest.bind(null, context))
    .on('response', function handleResponse(response) {
        response.on('data', onData.bind(null, context));

        return onResponse(context, response);
    })
    .on('end', onEnd.bind(null, context));
```

Note: Im not using streams

Cheers,
Emmet

**Comment by satazor** [comment] 2017-03-10 23:47
Duplicate of https://github.com/IndigoUnited/node-request-progress/issues/17

**Closed by satazor** 2017-03-10 23:47 UTC
