### ISSUE TITLE
windows problems with size total

### ISSUE THREAD

**Issue by gbaumgart** [IndigoUnited/node-request-progress#19] opened 2016-04-11 22:34 UTC
very often i get size.total undefined, Could you please check your lib with this url https://gitlab.com/xamiro/xcf-dist-windows/repository/archive.zip?ref=master

On windows I had to to add a callback to get the total via on('response') as alternative: 

.on('response', function (response,vas) {
            var len = parseInt(response.headers['content-length'], 10);

but its still never really reliable working, only on Linux its always working. I know that problems with other languages too. For instance if you download github tar balls, even browsers can't really determine the total sometimes. 

thanks!

**Comment by satazor** [comment] 2016-04-11 23:22
For me it's working all the time though I'm using MacOSx. I don't have windows at the moment, so it will be hard for me to debug.

**Comment by satazor** [comment] 2016-05-13 10:14
Closing because of no feedback.

**Closed by satazor** 2016-05-13 10:14 UTC

**Comment by gbaumgart** [comment] 2016-05-13 10:36
try a windows in a virtual machine. the bug is definitely there

**Comment by satazor** [comment] 2016-05-13 10:48
```
// foo.js
var fs = require('fs');
var request = require('request');
var progress = require('.');

// The options argument is optional so you can omit it
progress(request('https://gitlab.com/xamiro/xcf-dist-windows/repository/archive.zip?ref=master'))
.on('progress', function (state) {
    console.log('progress', state);
})
.on('error', function (err) {
    console.log('error', err);
})
.on('end', function () {
    console.log('ok!');
})
.pipe(fs.createWriteStream('archive.zip'));
```

Output:

![virtualbox_ie11 - win7_13_05_2016_12_47_54](https://cloud.githubusercontent.com/assets/1017236/15245772/f76e5c20-1908-11e6-8210-5bc16ada0072.png)

Windows 7
Node 4.4.2

**Comment by satazor** [comment] 2016-05-13 10:49
I'll need more information.. this is working fine to me.

**Comment by satazor** [comment] 2016-05-13 10:55
The only reason for this not be working for you is that you were behind a proxy that was removing headers.. as I said, if content-length header is not present, size will be `null`.

**Comment by gbaumgart** [comment] 2016-05-13 11:03
ok, i am not behind a proxy but ok. i fixed it by doing this here as said: 
progress.on('response', function (response) {
            var len = parseInt(response.headers['content-length'], 10);
            ... this happens not that often but it happens.
})

it seems also that gitlab and others actually create that file on request and at the time the download starts, the length isn't know yet. the second time (within the cache limits) its all ok. its not just gitlab but also github. 

anyhow, to me its still a bug.

**Comment by satazor** [comment] 2016-05-13 11:15
> it seems also that gitlab and others actually create that file on request and at the time the download starts, the length isn't know yet. the second time (within the cache limits) its all ok. its not just gitlab but also github.
anyhow, to me its still a bug.

That makes sense. Still it's not a bug.. if content-length is not sent by the server how can I determine the download size? It's impossible.

**Comment by gbaumgart** [comment] 2016-05-13 11:17
well, if wget and others can deal with that, and i still have to apply a fix then I really don't know your concept of 'robust software'. Sorry dude, its an edge case but still a case.

never mind, fixed on my side as said

**Comment by satazor** [comment] 2016-05-13 11:18
Could you take an uncached URL and do `curl -v [url] > archive.zip` and see the verbose output? You will see that `Content-Length` header is not present and no accurate progress will be displayed.

**Comment by satazor** [comment] 2016-05-13 11:22
I've taken a uncached github url and here's the output of wget..

<img width="1119" alt="screen shot 2016-05-13 at 13 20 33" src="https://cloud.githubusercontent.com/assets/1017236/15246490/885a41d2-190d-11e6-872c-3b1fe749be73.png">

As you see, the first attempt didn't show a progress bar.. the second one did because the content-length was known.. as you see, wget is not doing any voodoo to guess the content-size. This happens but it's not a bug.

**Comment by satazor** [comment] 2016-05-13 11:24
> never mind, fixed on my side as said

You haven't fixed it.. it appears to be fixed because the URL was cached..

**Comment by gbaumgart** [comment] 2016-05-13 11:28
weird, you're right. but I still need that extra fix, don't know why. the time progress kicks in, size still is empty and I pick it from the raw response and then can finally show the progress.

ok. no idea.
